name: holbegram
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_database: ^10.5.7
  cupertino_icons: ^1.0.6
  uuid: ^4.4.2
  image_picker: ^1.1.2
  bottom_navy_bar: ^6.1.0
  flutter_staggered_grid_view: ^0.4.0
  badges: ^2.0.2
  provider: ^6.0.5
  google_sign_in: ^5.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/user_placeholder.png
    - assets/icon/

  fonts:
      - family: Billabong
        fonts:
          - asset: assets/fonts/Billabong.ttf
      - family: InstagramSans
        fonts:
          - asset: assets/fonts/InstagramSans.ttf
          
flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon-appstore.png"
