// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';

import 'package:firebase_core/firebase_core.dart'
show FirebaseOptions;
import 'package:flutter/foundation.dart'
 show defaultTargetPlatform, kIsWeb, TargetPlatform;

String apiKey = dotenv.env['API_KEY'] ?? 'default_value';
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYg0PAVcS3x82ZQyV8NGBjI7oKvSlG5DA',
    appId: '1:428601249657:web:bad3d3e0ae93c70e98e9a8',
    messagingSenderId: '428601249657',
    projectId: 'holbegram-e8b78',
    authDomain: 'holbegram-e8b78.firebaseapp.com',
    storageBucket: 'holbegram-e8b78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgVJ0AlPwxNMueCX06O0szg2nPDCNUGVc',
    appId: '1:428601249657:android:85f48337d3cf1ac498e9a8',
    messagingSenderId: '428601249657',
    projectId: 'holbegram-e8b78',
    storageBucket: 'holbegram-e8b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnivFnli9MlphN7FRE_nFAOQLblxlv4jY',
    appId: '1:428601249657:ios:49e3b1aad4021a0598e9a8',
    messagingSenderId: '428601249657',
    projectId: 'holbegram-e8b78',
    storageBucket: 'holbegram-e8b78.appspot.com',
    iosBundleId: 'com.holbegram.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnivFnli9MlphN7FRE_nFAOQLblxlv4jY',
    appId: '1:428601249657:ios:3f9dd5cdd97c05dd98e9a8',
    messagingSenderId: '428601249657',
    projectId: 'holbegram-e8b78',
    storageBucket: 'holbegram-e8b78.appspot.com',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: '1:428601249657:web:e1a2f2fedabfbf8d98e9a8',
    messagingSenderId: '428601249657',
    projectId: 'holbegram-e8b78',
    authDomain: 'holbegram-e8b78.firebaseapp.com',
    storageBucket: 'holbegram-e8b78.appspot.com',
  );
}
